### ISSUE TITLE
[Sacred Gold] Silver's team is swapped

### ISSUE THREAD

**Issue by BoloDeMacaco** [domtronn/dc-nuzlocke#59] opened 2022-10-29 23:35 UTC
Silver's team in burned tower consists of:
Rival                        Murkrow Lv. 25, Magby Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Bayleef Lv. 27
Rival                        Murkrow Lv. 25, Elekid Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Quilava Lv. 27
Rival                        Murkrow Lv. 25, Elekid Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Croconaw Lv. 27

But the app is showing its Goldenrod team instead: 

Honchkrow (Lv. 45) @ None           /   Insomnia        /   Drill Peck, Toxic, Protect, Roost
Seadra (Lv. 44) @ None              /   Poison Point    /   Surf, Focus Energy, Ice Beam, DragonBreath
Magmar (Lv. 44) @ None              /   Flame Body      /   Flamethrower, Will-O-Wisp, Focus Blast, Psychic
Gengar (Lv. 45) @ None              /   Levitate        /   Shadow Ball, Giga Drain, Thunder, Hypnosis
Alakazam (Lv. 45) @ None            /   Synchronize     /   Psychic, Shock Wave, Energy Ball, Thunder Wave
Meganium (Lv. 46) @ None            /   Overgrow        /   Seed Bomb, Reflect, Swords Dance, Body Slam

Rival
Honchkrow (Lv. 45) @ None           /   Insomnia        /   Drill Peck, Toxic, Protect, Roost
Seadra (Lv. 44) @ None              /   Poison Point    /   Surf, Focus Energy, Ice Beam, DragonBreath
Electabuzz (Lv. 44) @ None          /   Static          /   Thunderbolt, Thunder Wave, Psychic, Focus Blast
Gengar (Lv. 45) @ None              /   Levitate        /   Shadow Ball, Giga Drain, Thunder, Hypnosis
Alakazam (Lv. 45) @ None            /   Synchronize     /   Psychic, Shock Wave, Energy Ball, Thunder Wave
Typhlosion (Lv. 46) @ None          /   Blaze           /   Flamethrower, Focus Blast, Rock Slide, Shadow Claw

Rival
Honchkrow (Lv. 45) @ None           /   Insomnia        /   Drill Peck, Toxic, Protect, Roost
Magmar (Lv. 44) @ None              /   Flame Body      /   Flamethrower, Will-O-Wisp, Focus Blast, Psychic
Electabuzz (Lv. 44) @ None          /   Static          /   Thunderbolt, Thunder Wave, Psychic, Focus Blast
Gengar (Lv. 45) @ None              /   Levitate        /   Shadow Ball, Giga Drain, Thunder, Hypnosis
Alakazam (Lv. 45) @ None            /   Synchronize     /   Psychic, Shock Wave, Energy Ball, Thunder Wave
Feraligatr (Lv. 46) @ None          /   Torrent         /   Waterfall, Crunch, Ice Fang, Swords Dance

Also you cant find the Goldenrod Rival fight in the app

**Comment by domtronn** [comment] 2023-03-03 15:05
Thanks for raising this issue! 
Just refamiliarising myself and you're right - the Burned Tower and Goldenrod fights are missing.

All trainer data for Storm Silver & Sacred Gold comes from this [Google Doc](https://drive.google.com/file/d/1UQij-NGr2RpXXu7VNWJUIjtwtWBHxLfb/view) as a reference... But unfortunately, these two rival fights are missing move information, which is why I must have left them out.

Do you know of any sources where I could find that data?

**Comment by BoloDeMacaco** [comment] 2023-03-03 16:38
https://drive.google.com/drive/folders/1oSurQpYjTCMBxC3G6g3vcxsqBjI04ILT
here

Em sex., 3 de mar. de 2023 às 12:06, Dom Charlesworth <
***@***.***> escreveu:

**Comment by domtronn** [comment] 2023-03-09 22:03
Yeah that's the doc I linked to for using as a reference.

As I say, both of these fights are missing the movesets for the pokémon which is why they're left out. i.e.

```
Burned Tower
=================================================================================================================================================
Rival                        Murkrow Lv. 25, Magby Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Bayleef Lv. 27
Rival                        Murkrow Lv. 25, Elekid Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Quilava Lv. 27
Rival                        Murkrow Lv. 25, Elekid Lv. 24, Haunter Lv. 25, Kadabra Lv. 26, Croconaw Lv. 27

Goldenrod City
=================================================================================================================================================
Rival                        Honchkrow Lv. 45, Seadra Lv. 44, Magmar Lv. 44, Gengar Lv. 45, Alakazam Lv. 45, Meganium Lv. 46
Rival                        Honchkrow Lv. 45, Seadra Lv. 44, Electabuzz Lv. 44, Gengar Lv. 45, Alakazam Lv. 45, Typhlosion Lv. 46
Rival                        Honchkrow Lv. 45, Magmar Lv. 44, Electabuzz Lv. 44, Gengar Lv. 45, Alakazam Lv. 45, Feraligatr Lv. 46
```

I could add in the teams without moves I guess? But that still feels broken.
Do you know the movesets/abilities for these teams?

**Comment by domtronn** [comment] 2023-04-10 11:59
I've updated these two encounters with the level up learnsets for each pokémon.
I think this is the intended behaviour. I've also added the locations for these encounters properly so it should be fixed now 👍

**Closed by domtronn** 2023-04-10 11:59 UTC
